# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:                 "Tanner S"
subtitle:              "Portfolio Site"
logo:                  "assets/images/site-logo-ts.png"
favcon:                "assets/images/favicon.ico"
email:                 tssullivan115@icloud.com
hidemyemail:           "vogues-jade-0r@icloud.com"
description:           "Welcome to my portfolio site. As I level up, I hope to share some of my favorite projects in this portfolio site. The works included here are focused on technical writing, but who knows what I may explore!"
twitter_username:      sulliespace
github_username:       tannersullie
github:                https://github.com/tannersullie/writersite
search:                true

# Build settings
markdown:              kramdown
remote_theme:          mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
timezone: America/Chicago
date_format: "%Y-%m-%d"
url: https://www.tannerswriting.site
og_image: /assets/images/og-ref-img.png
# Outputting
permalink:             /:categories/:title/
paginate:              5 # amount of posts to show
paginate_path:         /page:num/
timezone:              # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones



include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-email-protect
  - jekyll-seo-tag

author:
  name   :             "Tanner Sullivan, MA"
  avatar :             "/assets/images/drk-memoji.jpg"
  bio    :             "Tech Writer (& Foodie) at 💖"
  repository:          "tannersullie/writersite"
  location:            "Arkansas, US"
  links:
    - label:           "GitHub"
      icon:            "fab fa-fw fa-github"
      url:             "https://github.com/tannersullie"
    - label:           "LinkedIn"
      icon:            "fab fa-fw fa-linkedin"
      url:             "https://www.linkedin.com/in/tanner-sullivan-m-a-184491121/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-MY06YS4J4B"
    anonymize_ip:  false # default

footer:
  links:
#    - label:           "Twitter"
#      icon:            "fab fa-fw fa-twitter-square"
#      url:             "https://twitter.com/sulliespace"
    - label:           "GitHub"
      icon:            "fab fa-fw fa-github"
      url:             "https://github.com/tannersullie"
    - label:           "LinkedIn"
      icon:            "fab fa-fw fa-linkedin"
      url:             "https://www.linkedin.com/in/tanner-sullivan-m-a-184491121/"
    - label:           "Post Archives"
      icon:            "fas fa-archive"
      url:             /meta-archives/
    - label:           "Privacy Policy"
      icon:            "fas fa-user-secret"
      url:             /privacy-policy/


defaults:
  # _posts
  - scope:
      path:            ""
      type:            posts
    values:
      layout:          single
      author_profile:  true
      read_time:       true
      comments:        true
      share:           true
      related:         true
    # header:
    #   overlay_color: "#000"
    #   overlay_filter: linear-gradient(90deg, hsla(40, 1%, 43%, 1) 0%, hsla(42, 51%, 83%, 1) 100%); # gray to bone
    #   show_overlay_excerpt: true
    #   teaser: /assets/images/og-ref-img.png
  # _pages
  - scope:
      path:            "_pages"
      type:            pages
    values:
      layout:          single
      author_profile:  true
      show_date:       true
    header:
      overlay_color: "#000"
      overlay_filter: linear-gradient(90deg, hsla(48, 32%, 24%, 1) 0%, hsla(42, 89%, 70%, 1) 100%); # dark to goldenrod
      show_overlay_excerpt: true
      teaser: /assets/images/og-ref-img.png
  # Professional-artifacts
  - scope:
      path: "/professional-artifacts"
      type: professional-artifacts
    values:
      layout: collection
      author_profile: false
      share: true
    breadcrumbs: true #disabled by default
    header:
      overlay_color: "#000"
      overlay_filter: linear-gradient(90deg, hsla(269, 33%, 21%, 1) 0%, hsla(262, 8%, 48%, 1) 100%); # gradient lavendar
      show_overlay_excerpt: true
      teaser: /assets/images/og-ref-img.png
  # Educational-artifacts
  - scope:
      path: "/_highered-artifacts/"
      type: highered-artifacts
    values:
      layout: collection
      author_profile: false
      share: true
    breadcrumbs: true #disabled by default
    header:
      overlay_color: "#000"
      overlay_filter: linear-gradient(90deg, hsla(48, 32%, 24%, 1) 0%, hsla(42, 89%, 70%, 1) 100%); # dark to goldenrod
      show_overlay_excerpt: true
      teaser: /assets/images/og-ref-img.png
  # Explorative-artifacts
  - scope:
      path: "/_personal-projects/"
      type: personal-projects
    values:
      layout: collection
      author_profile: true
      share: true
    breadcrumbs: true #disabled by default
    header:
      overlay_color: "#000"
      overlay_filter: linear-gradient(90deg, hsla(269, 33%, 21%, 1) 16%, hsla(262, 78%, 31%, 1) 86%, hsla(262, 78%, 51%, 1) 100%); # three point indigo gradient
      show_overlay_excerpt: true
      teaser: /assets/images/og-ref-img.png

# header:
#   overlay_color: "#000"
#   linear-gradient(90deg, hsla(263, 32%, 24%, 1) 0%, hsla(262, 78%, 51%, 1) 61%, hsla(42, 89%, 70%, 1) 100%); #lavender to electric to yellow
#   show_overlay_excerpt: true
# alternatives
#   overlay_filter: linear-gradient(90deg, hsla(40, 1%, 43%, 1) 0%, hsla(42, 51%, 83%, 1) 100%); # gray to bone
#   overlay_filter: linear-gradient(90deg, hsla(48, 32%, 24%, 1) 0%, hsla(42, 89%, 70%, 1) 100%); # dark to goldenrod
#   overlay_filter: linear-gradient(90deg, hsla(271, 37%, 17%, 1) 0%, hsla(262, 78%, 51%, 1) 100%); # Gradient Indigo
#   background: linear-gradient(90deg, hsla(269, 33%, 21%, 1) 0%, hsla(262, 8%, 48%, 1) 100%); # Gradient Lavendar
# writer header
#   header:
#       overlay_image: /assets/images/group-of-writers.png
#       image_description: "Writers around books banner placeholder"
#       overlay_filter: .3 
#       show_overlay_excerpt: true


category_archive:
  type:                liquid
  path:                /categories/
tag_archive:
  type:                liquid
  path:                /tags/
collections:
  professional-artifacts:
    output: true
    permalink: /:collection/:path/
  highered-artifacts:
    output: true
    permalink: /:collection/:path/
  personal-projects:
    output: true
    permalink: /:collection/:path/

jekyll_admin:
  homepage: "posts"