# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:                 Tanner's Writing Site
subtitle:              "My Portfolio"
logo:                  "/assets/images/TS-Logo2021-blacknwhite.png"
email:                 tssullivan115@icloud.com
description:           >- # this means to ignore newlines until "baseurl:"
  As I level up, I hope to share some of my favorite projects in this portfolio site.
  The works included here are focused on technical writing, but who knows what I may explore!
twitter_username:      sulliespace
github_username:       tannersullie
github: [metadata]
minimal_mistakes_skin: default
search:                true

# Build settings
markdown:              kramdown
remote_theme:          mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
timezone: America/Chicago
url: https://www.tannerswriting.site
og_image: /assets/images/TS-Logo2021-blacknwhite.png
# Outputting
permalink:             /:categories/:title/
paginate:              5 # amount of posts to show
paginate_path:         /page:num/
timezone:              # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   :             "Tanner Sullivan"
  avatar :             "/assets/images/author-pic.png"
  bio    :             "M.A in Professional and Technical Writing"
  repository:          "tannersullie/writersite"
  location:            "Arkansas, US"
  links:
    - label:           "Website"
      icon:            "fas fa-fw fa-link"
      url:             "https://www.tannerswriting.site"
    - label:           "Twitter"
      icon:            "fab fa-fw fa-twitter-square"
      url:             "https://twitter.com/"
    - label:           "GitHub"
      icon:            "fab fa-fw fa-github"
      url:             "https://github.com/tannersullie"
    - label:           "LinkedIn"
      icon:            "fab fa-fw fa-linkedin"
      url:             "https://www.linkedin.com/in/tanner-sullivan-184491121/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B%2BWCNEXP5RjqwoVrS5yETYg%3D%3D"

footer:
  links:
    - label:           "Twitter"
      icon:            "fab fa-fw fa-twitter-square"
      url:             "https://twitter.com/"
    - label:           "GitHub"
      icon:            "fab fa-fw fa-github"
      url:             "https://github.com/tannersullie"
    - label:           "LinkedIn"
      icon:            "fab fa-fw fa-linkedin"
      url:             "https://www.linkedin.com/in/tanner-sullivan-184491121/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B%2BWCNEXP5RjqwoVrS5yETYg%3D%3D"
    - label:           "Post Archives"
      icon:            "fas fa-archive"
      url:             /meta-archives/

defaults:
  # _posts
  - scope:
      path:            ""
      type:            posts
    values:
      layout:          single
      author_profile:  true
      read_time:       true
      comments:        true
      share:           true
      related:         true
  # _pages
  - scope:
      path:            "_pages"
      type:            pages
    values:
      layout:          single
      author_profile:  true
      show_date:       true
    breadcrumbs:           true #disabled by default


category_archive:
  type:                liquid
  path:                /categories/
tag_archive:
  type:                liquid
  path:                /tags/
